version: '3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - ci_network
    user: root

networks:
  ci_network:
    driver: bridge

volumes:
  jenkins_home:
